### ISSUE TITLE
v0.7 statx compile fail with kernels before 4.10

### ISSUE THREAD

**Issue by zenfey** [ocaml-multicore/ocaml-uring#106]
Hi, PR #95 will include  <linux/stat.h> to deal with earlier systems with undefined STATX_TYPE, it seems old versions kernel headers before 4.10 do not contain definition of STATX in this header file.

On my centos 7 machine with kernel version 3.10 LTS, the compile error occured on line 442 of uring_stubs.c, prompting "invalid application of 'sizeof' to incomplete type 'struct statx'".

Elrepo is an option for me to update system kernel to mainline version (>5.1) so to support syscalls of statx and io_uring  at all on centos7, but I'm afraid this may get things into totally mess.

Could some additional macros be added so as to bypass statx compilation, thx : )

**Comment by talex5** [comment]
Happy to accept a PR for that, if you can find something that works!

**Comment by avsm** [comment]
Why are you compiling io_uring on such an old kernel? It won't reliably work with anything older than 5.11, and preferably 6.1.

**Comment by talex5** [comment]
I assume it's for programs that depend on eio_main, which uses eio_linux if the running kernel is new enough (so you still need to be able to compile it). Perhaps we just need an OS version constraint in `eio_main`'s dependency to fix that?

**Comment by zenfey** [comment]
> Why are you compiling io_uring on such an old kernel? It won't reliably work with anything older than 5.11, and preferably 6.1.

Some vendor provided libraries have dependency on specified version of libssl. I tried to compile install this libssl form source on machines with Rocky 9 and openSUSE 15 both have kernel version higher than 5.11 but still have linking problems.

I've got no idea why procedures with eio with uring(<=0.6) can run on a kernel that doesn't support liburing. Timer, net, fiber and green threads all work in a good state. The benchmark of flow.copy is also significant. I guess some constraint can bypass liburing when meeting async io on old machines? Could someone explain, thanks: )

**Comment by chris-armstrong** [comment]
Not sure if this is of any help, but I'm trying to compile iouring on a ~5.10 series kernel, and found I needed to make [this change](https://github.com/ocaml-multicore/ocaml-uring/pull/110) to get it to compile (the system I'm targeting is Amazon Linux 2, which uses an old kernel version, but is still maintained, as it used in AWS Lambda provided runtimes).

**Comment by talex5** [comment]
> I've got no idea why procedures with eio with uring(<=0.6) can run on a kernel that doesn't support liburing.

It checks the kernel version at runtime and switches to eio_posix if it's too old.

I've added an opam constraint to ignore eio_linux on centos 7:

https://github.com/ocaml-multicore/eio/pull/638

**Comment by zenfey** [comment]
> > I've got no idea why procedures with eio with uring(<=0.6) can run on a kernel that doesn't support liburing.
> 
> It checks the kernel version at runtime and switches to eio_posix if it's too old.
> 
> I've added an opam constraint to ignore eio_linux on centos 7:
> 
> [ocaml-multicore/eio#638](https://github.com/ocaml-multicore/eio/pull/638)

I'v just opam upgraded packages and uring 0.8 is certainly failed to compile on centos7,  while eio comes to version 0.13 successfully. cheers :+1:
