### ISSUE TITLE
`wait`: Report to the caller if there are no pending operations

### ISSUE THREAD

**Issue by copy** [ocaml-multicore/ocaml-uring#66]
If I understand it correctly, `Uring.wait` will sleep forever if called on an idle ring (with no operations pending). It would be nice to expose this somehow, either by changing its return type or adding a separate function. It seems that a mechanism for this already exists (`Uring.exit` check for it, for example).

**Comment by talex5** [comment]
What do you need it for?
- `Uring.peek` will report if there are completed operations without blocking (I'm going to rename this).
- `Uring.get_debug_stats` will tell you if there any operations in progress at all.

**Comment by haesbaert** [comment]
If/when we decouple the CQEs from SQEs it might make sense to expose the number pending CQEs as a normal thing though (outside debug), as the user shouldn't rely on pending jobs as the accumulation of returns of `Uring.submit`. ATM we end up calling `submit` and discarding the return in other places in the stubs as well.

**Comment by talex5** [comment]
Fixed in #68.
